import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../models/government_scheme_models.dart';

class PdfService {
  Future<String> generateApplicationPdf(
    SchemeApplication application, 
    GovernmentScheme scheme
  ) async {
    final pdf = pw.Document();
    
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            _buildHeader(scheme),
            pw.SizedBox(height: 20),
            _buildApplicationDetails(application),
            pw.SizedBox(height: 20),
            _buildFormData(application, scheme),
            pw.SizedBox(height: 20),
            _buildFooter(application),
          ];
        },
      ),
    );

    return await _savePdf(pdf, application.id);
  }

  pw.Widget _buildHeader(GovernmentScheme scheme) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(width: 2),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Text(
            'Government Scheme Application',
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            scheme.name,
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.Text(
            scheme.nameHindi,
            style: const pw.TextStyle(fontSize: 14),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildApplicationDetails(SchemeApplication application) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Application Details',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 8),
          _buildDetailRow('Application ID:', application.id),
          _buildDetailRow('Tracking Number:', application.trackingNumber ?? 'N/A'),
          _buildDetailRow('Application Date:', 
            _formatDate(application.appliedDate)),
          _buildDetailRow('Status:', _getStatusText(application.status)),
        ],
      ),
    );
  }

  pw.Widget _buildFormData(SchemeApplication application, GovernmentScheme scheme) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Form Details',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 8),
          ...scheme.requiredFields.map((field) {
            final value = application.formData[field.id]?.toString() ?? 'N/A';
            return _buildDetailRow('${field.label}:', value);
          }),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(SchemeApplication application) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Important Notes:',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            '• Keep this document safe for future reference',
            style: const pw.TextStyle(fontSize: 12),
          ),
          pw.Text(
            '• Track your application status using the tracking number',
            style: const pw.TextStyle(fontSize: 12),
          ),
          pw.Text(
            '• Generated by Kisan Vaani App',
            style: const pw.TextStyle(fontSize: 10),
          ),
          pw.SizedBox(height: 20),
          pw.Text(
            'Generated on: ${_formatDate(DateTime.now())}',
            style: const pw.TextStyle(fontSize: 10),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildDetailRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 150,
            child: pw.Text(
              label,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value),
          ),
        ],
      ),
    );
  }

  String _formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }

  String _getStatusText(ApplicationStatus status) {
    switch (status) {
      case ApplicationStatus.draft:
        return 'Draft';
      case ApplicationStatus.submitted:
        return 'Submitted';
      case ApplicationStatus.underReview:
        return 'Under Review';
      case ApplicationStatus.approved:
        return 'Approved';
      case ApplicationStatus.rejected:
        return 'Rejected';
      case ApplicationStatus.documentsPending:
        return 'Documents Pending';
      case ApplicationStatus.paymentProcessing:
        return 'Payment Processing';
      case ApplicationStatus.completed:
        return 'Completed';
    }
  }

  Future<String> _savePdf(pw.Document pdf, String applicationId) async {
    final directory = await getSchemeDocumentsDirectory();
    final filePath = '${directory.path}/application_$applicationId.pdf';
    
    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());
    
    return filePath;
  }

  Future<Directory> getSchemeDocumentsDirectory() async {
    final appDir = await getApplicationDocumentsDirectory();
    final documentsDir = Directory('${appDir.path}/government_schemes');
    
    if (!documentsDir.existsSync()) {
      await documentsDir.create(recursive: true);
    }
    
    return documentsDir;
  }

  Future<List<File>> getStoredPdfs() async {
    try {
      final directory = await getSchemeDocumentsDirectory();
      final files = directory.listSync()
          .where((file) => file.path.endsWith('.pdf'))
          .cast<File>()
          .toList();
      
      return files;
    } catch (e) {
      return [];
    }
  }

  Future<void> deletePdf(String filePath) async {
    try {
      final file = File(filePath);
      if (await file.exists()) {
        await file.delete();
      }
    } catch (e) {
      print('Error deleting PDF: $e');
    }
  }
}
